name: "Test"

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "18 18 * * 1,3,5"
  push:
    branches: ["**"]
    paths:
      - "dist/**"
      - "src/**"
      - "package*.json"
      - "requirements*.txt"
      - ".github/workflows/test.yaml"
      - "action.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Debug event.json"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "1 - Test File"
        uses: ./
        with:
          file: ".github/labels.yaml"
          delete: true
          dry-run: true

      - name: "Delete Local File"
        if: ${{ !github.event.act }}
        run: rm -rf .github/labels.yaml

      - name: "2 - Test API"
        if: ${{ !github.event.act }}
        uses: ./
        with:
          file: ".github/labels.yaml"

      - name: "3 - Test URL"
        if: ${{ !github.event.act }}
        uses: ./
        with:
          url: "https://raw.githubusercontent.com/cssnr/label-creator-action/refs/heads/master/.github/labels.yaml"

      - name: "4 - Test JSON"
        if: ${{ !github.event.act }}
        uses: ./
        with:
          file: "https://raw.githubusercontent.com/cssnr/label-creator-action/refs/heads/master/.github/labels.yaml"
          json: |
            {
              "workflows": {"color": "ffffff", "description": "Workflows modification"},
              "source": {"color": "fbca04", "description": "Source modification"},
              "documentation": {"color": "0075ca", "description": "Documentation updates"}
            }

      - name: "Schedule Failure Notification"
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
