name: "Test"

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "18 18 * * 1,3,5"
  push:
    branches: ["**"]
    paths:
      - "dist/**"
      - "src/**"
      - "package*.json"
      - "requirements*.txt"
      - ".github/workflows/test.yaml"
      - "action.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Debug event.json"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "1 - Test File"
        id: test1
        uses: ./
        with:
          file: ".github/labels.yaml"

      - name: "1 - Verify File"
        run: |
          echo "created: ${{ steps.test1.outputs.created }}"
          echo "updated: ${{ steps.test1.outputs.updated }}"

      #- name: "2 - Test URL"
      #  id: test1
      #  uses: ./
      #  with:
      #    file: "https://raw.githubusercontent.com/cssnr/label-creator-action/refs/heads/master/.github/labels.yaml"

      #- name: "2 - Verify URL"
      #  run: |
      #    echo "created: ${{ steps.test1.outputs.created }}"
      #    echo "updated: ${{ steps.test1.outputs.updated }}"

      #- name: "3 - Test JSON"
      #  id: test2
      #  uses: ./
      #  with:
      #    file: "https://raw.githubusercontent.com/cssnr/label-creator-action/refs/heads/master/.github/labels.yaml"
      #    json: |
      #      {
      #        "source": {"color": "FBCA04", "description": "Source modifications"},
      #        "documentation": {"color": "0052CC", "description": "Documentation updates"}
      #      }

      #- name: "3 - Verify JSON"
      #  run: |
      #    echo "created: ${{ steps.test2.outputs.created }}"
      #    echo "updated: ${{ steps.test2.outputs.updated }}"

      #- name: "Schedule Failure Notification"
      #  if: ${{ failure() && github.event_name == 'schedule' }}
      #  uses: sarisia/actions-status-discord@v1
      #  with:
      #    webhook: ${{ secrets.DISCORD_WEBHOOK }}
